### ISSUE TITLE
Support for Cordova 4.1

### ISSUE THREAD

**Issue by Jul13nT** [mgwt/gwtphonegap#6]
I would like to know as well when it will be upgraded to support a more recent version. I need at least the 4.1.1 version as Google said : https://support.google.com/faqs/answer/6325474

**Comment by waynedyck** [comment]
The current version supports the latest Cordova 6.0.0 build.

I had the same issue with my [Seattle Traffic Flow](https://play.google.com/store/apps/details?id=com.imaginedreal.trafficflow) app and I upgraded Cordova to 6.0.0 and continued to use gwt-phonegap 3.5.0.0 without issue.

**Comment by Jul13nT** [comment]
Ok thank you, i will try to upgrade in the next few weeks.

**Comment by waynedyck** [comment]
Sounds good. If you have any questions, let me know.
